server:
  port: 7070

spring:
  application:
    name: "loans"

  profiles:
    active: "prod"

  datasource:
    url: jdbc:mysql://loansdb:3306/loansDB?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://configserver:8071/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
     defaultZone: http://eurekaserver:8070/eureka/

info:
  app:
    name: "loans-ms"
    description: "EazyBank loans-Microservice"
    version: "1.0.0"