server:
  port: 8080

spring:
  application:
    name: "accounts"
  profiles:
    active: "PROD"        # Make sure 'PROD' profile exists

  datasource:
    url: jdbc:mysql://accountsdb:3306/accountsDB?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://configserver:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

info:
  app:
    name: "accounts-ms"
    description: "Eazy Bank Accounts-Microservice"
