server:
  port: 8080

spring:
  application:
    name: "accounts"
  profiles:
    active: "PROD"        # case doesn’t matter

  datasource:
    url: jdbc:mysql://accountsdb:3306/accountsDB   # host = localhost, db = accountsdb
    username: root
    password: root                                 # use whatever you set in docker
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://configserver-ms:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
