version: "3.9"

services:
  accountsdb:
    extends:
      file: common-config.yml
      service: microservice-db-config
    image: mysql
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsDB

  loansdb:
    extends:
      file: common-config.yml
      service: microservice-db-config
    image: mysql
    container_name: loansdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loansDB

  cardsdb:
    extends:
      file: common-config.yml
      service: microservice-db-config
    image: mysql
    container_name: cardsdb
    ports: 
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cardsDB

  configserver:
    extends:
      file: common-config.yml
      service:  microservice-base-config
    image: "bhimesh1998/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s 

  accounts:
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    image: "bhimesh1998/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsDB"
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy

  loans:
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    image: "bhimesh1998/loans:v1"
    container_name: loans-ms
    ports:
      - "7070:7070"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansDB"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy

  cards:
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    image: "bhimesh1998/cards:v1"
    container_name: cards-ms
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsDB"
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy

networks:
  bhimesh06:
    driver: "bridge"
